baseURL = "https://www.blerf.ca/"
title = "Blerf"
languageCode = "en-us"

author = "Sam Pillsworth"
copyright = "Sam Pillsworth  - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)"

theme = "hugo-ficurinia"
summaryLength = 30

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 2
    style = "witchhazel"

[params]
  description = "blerfer of blerfs"
  posts = "words"
  showPostsLink = false
  extraContentDirs = ["words"]

  logo = "/images/profile.png"
  favicon = "/images/favicon.png"
  faviconIco = "/images/favicon.ico"
  appletouch = "/images/apple-touch-icon.png"
  icon512 = "/images/android-chrome-512x512.png"

  fontFamily = "Fantasque Sans Mono"  # changes the font, default "JetBrains Mono"
  titleFontFamily = "Fantasque Sans Mono"  # font used for titles and headings
  monospaceFontFamily = "Fantasque Sans Mono"  # changes the monospace font for code, default "JetBrains Mono"


[menu]
  [[menu.icons]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/samspills"
    weight = 10
  [[menu.icons]]
    identifier = "mastodon"
    name = "Mastodon"
    url = "https://weirder.earth/@spills"
    weight = 20

# ox-hugo required
[markup.goldmark.renderer]
  unsafe = true
